"""Fail-closed atomic Oracle execution infrastructure."""

from .atoms import (
    ArtifactIdentityNormalizer,
    BooleanInvariantComparator,
    CanonicalDecimalNormalizer,
    ConsensusEqualityComparator,
    ExactEqualityComparator,
    GoldenArtifactComparator,
    RatioUpperBoundComparator,
    RunStatusNormalizer,
    ScalarEstimate,
    Utf8ArtifactNormalizer,
)
from .catalog import AtomicOracleCatalog, CatalogError
from .engine import (
    ArtifactIntegrityError,
    AtomicOracleEngine,
    AtomicOracleError,
    AtomicOracleErrorCode,
)
from .model import (
    ApplicabilityResult,
    AtomicCapturedArtifact,
    AtomicComparator,
    AtomicDataError,
    AtomicNormalizer,
    AtomicOracleResult,
    AtomicResultClass,
    AtomicRunRecord,
    AtomicRunner,
    AtomicRunRequest,
    AtomicRunResult,
    AtomicRunStatus,
    AtomicTrialRecord,
    AtomicVariantBinding,
    NormalizedValue,
    TrialDecision,
)

__all__ = [
    "ApplicabilityResult",
    "ArtifactIdentityNormalizer",
    "ArtifactIntegrityError",
    "AtomicCapturedArtifact",
    "AtomicComparator",
    "AtomicDataError",
    "AtomicNormalizer",
    "AtomicOracleCatalog",
    "AtomicOracleEngine",
    "AtomicOracleError",
    "AtomicOracleErrorCode",
    "AtomicOracleResult",
    "AtomicResultClass",
    "AtomicRunRecord",
    "AtomicRunner",
    "AtomicRunRequest",
    "AtomicRunResult",
    "AtomicRunStatus",
    "AtomicTrialRecord",
    "AtomicVariantBinding",
    "BooleanInvariantComparator",
    "CanonicalDecimalNormalizer",
    "CatalogError",
    "ConsensusEqualityComparator",
    "ExactEqualityComparator",
    "GoldenArtifactComparator",
    "NormalizedValue",
    "RatioUpperBoundComparator",
    "RunStatusNormalizer",
    "ScalarEstimate",
    "TrialDecision",
    "Utf8ArtifactNormalizer",
]
